export const version = '0.3.0'

export type ReferenceEntry = readonly [
  category: string,
  identifier: string,
  description: string,
  required: string,
  defaultValue: string,
  hostContract: string,
  example: string,
]

export const navigation = [
  ['quick-start', 'Quick start'],
  ['examples', 'Live examples'],
  ['concepts', 'Concepts'],
  ['recipes', 'Recipes'],
  ['reference', 'Reference'],
  ['accessibility', 'Accessibility'],
  ['platforms', 'Platform notes'],
  ['release-notes', 'Versions and migration'],
] as const

export const referenceEntries: ReferenceEntry[] = [
  [
    'Chat',
    'Chat',
    'Controlled chat surface for messages, composer, history, and states.',
    'required',
    'None',
    'The host owns messages, draft, status, and callbacks.',
    '<Chat messages={messages} draft={draft} status={status} />',
  ],
  [
    'Chat',
    'messages',
    'Ordered message records rendered in the reading column.',
    'required',
    '[]',
    'Supply stable ids, roles, content parts, and statuses.',
    'messages={messages}',
  ],
  [
    'Chat',
    'draft',
    'Current composer text.',
    'required',
    "''",
    'Update it from onChangeDraft.',
    'draft={draft}',
  ],
  [
    'Chat',
    'status',
    'Conversation operation status.',
    'required',
    "'idle'",
    'Set it from host or useChatSession.',
    "status='idle'",
  ],
  [
    'Chat',
    'hasEarlierMessages',
    'Whether history can load older messages.',
    'required',
    'false',
    'Set true when the host has another page.',
    'hasEarlierMessages={hasEarlierMessages}',
  ],
  [
    'Chat',
    'isLoadingEarlier',
    'Whether an earlier-message request is active.',
    'required',
    'false',
    'Use to keep the history control deterministic.',
    'isLoadingEarlier={isLoadingEarlier}',
  ],
  [
    'Chat',
    'onChangeDraft',
    'Receives each draft edit.',
    'required',
    'None',
    'Store the next draft value in host state.',
    'onChangeDraft={setDraft}',
  ],
  [
    'Chat',
    'onSubmit',
    'Receives a non-empty submitted prompt.',
    'required',
    'None',
    'Start or delegate an operation.',
    'onSubmit={submit}',
  ],
  [
    'Chat',
    'onStop',
    'Requests cooperative cancellation.',
    'required',
    'None',
    'Abort transport and retain partial content.',
    'onStop={stop}',
  ],
  [
    'Chat',
    'onLoadEarlier',
    'Requests older messages.',
    'required',
    'None',
    'Prepend records while preserving the visible anchor.',
    'onLoadEarlier={loadEarlier}',
  ],
  [
    'Chat',
    'onMessageAction',
    'Receives copy, retry, or regenerate actions.',
    'optional',
    'None',
    'Perform clipboard or operation work in the host.',
    'onMessageAction={onMessageAction}',
  ],
  [
    'Chat',
    'messageRenderer',
    'Replaces complete message rendering.',
    'optional',
    'Default renderer',
    'Return a renderer with fallback for unsupported records.',
    'messageRenderer={MessageRenderer}',
  ],
  [
    'Chat',
    'contentRenderer',
    'Replaces a content-part renderer.',
    'optional',
    'Default renderer',
    'Render matching text content and delegate other parts.',
    'contentRenderer={ContentRenderer}',
  ],
  [
    'Chat',
    'markdownRenderer',
    'Replaces Markdown rendering.',
    'optional',
    'MarkdownRenderer',
    'Keep unsafe HTML and remote images inert.',
    'markdownRenderer={MarkdownRenderer}',
  ],
  [
    'Chat',
    'theme',
    'Selects or supplies semantic theme tokens.',
    'optional',
    'Light theme',
    'Use light, dark, or high-contrast values.',
    "theme='dark'",
  ],
  [
    'Chat',
    'styleOverrides',
    'Overrides documented surfaces and layout tokens.',
    'optional',
    'None',
    'Preserve readable contrast and focus affordances.',
    'styleOverrides={styleOverrides}',
  ],
  [
    'Chat',
    'capabilities',
    'Enables or disables capability-gated controls.',
    'optional',
    'All supported capabilities',
    'Reflect transport and host policy.',
    'capabilities={{ canCopy: false }}',
  ],
  [
    'Chat',
    'labels',
    'Replaces accessible labels and visible control text.',
    'optional',
    'Built-in labels',
    'Keep labels concise and translated where needed.',
    'labels={{ send: "Send" }}',
  ],
  [
    'useChatSession',
    'useChatSession',
    'Operation-aware state controller for transport-backed hosts.',
    'optional',
    'None',
    'Connect request controls to Chat props.',
    'const session = useChatSession({ request })',
  ],
  [
    'useChatSession',
    'request',
    'Starts one operation and receives transport controls.',
    'required',
    'None',
    'Call appendChunk, complete, fail, and observe stopRequested.',
    'request: async (operation, controls) => {}',
  ],
  [
    'useChatSession',
    'appendChunk',
    'Appends current-operation response text.',
    'required in streaming',
    'None',
    'Only current operation updates are accepted.',
    'controls.appendChunk(chunk)',
  ],
  [
    'useChatSession',
    'complete',
    'Marks current response complete and chat idle.',
    'required terminal call',
    'None',
    'Call once when transport finishes.',
    'controls.complete()',
  ],
  [
    'useChatSession',
    'fail',
    'Marks the message error and returns chat to idle.',
    'required terminal call on error',
    'None',
    'Partial content remains and retry stays available.',
    'controls.fail()',
  ],
  [
    'useChatSession',
    'stopRequested',
    'Reports cooperative stop state.',
    'required in streaming',
    'false',
    'Break transport work when true.',
    'if (controls.stopRequested()) return',
  ],
  [
    'Message',
    'Message',
    'Message record with stable identity and content parts.',
    'required',
    'None',
    'Host validates ids and supplies role, content, timestamps, and status.',
    'const message: Message = { id, role, contentParts, status, createdAt }',
  ],
  [
    'Content',
    'ContentPart',
    'Current content model: text in plain or Markdown format.',
    'required',
    'text/plain',
    'Do not send images, attachments, or tool calls.',
    "{ type: 'text', format: 'markdown', text }",
  ],
  [
    'Status',
    'MessageStatus',
    'queued, sending, streaming, complete, stopped, or error.',
    'required',
    "'complete'",
    'A failed message retains partial content and marks error.',
    "status: 'streaming'",
  ],
  [
    'Status',
    'ChatStatus',
    'Conversation-level idle or active status.',
    'required',
    "'idle'",
    'A failed message returns the conversation to idle.',
    "status='idle'",
  ],
  [
    'Renderers',
    'MarkdownText',
    'Default Markdown text renderer.',
    'optional',
    'Built-in',
    'Raw HTML and remote images are not rendered by default.',
    '<MarkdownText text={text} />',
  ],
  [
    'Renderers',
    'PlainText',
    'Plain user-text renderer.',
    'optional',
    'Built-in',
    'User content is rendered as inert text.',
    '<PlainText text={text} />',
  ],
  [
    'Renderers',
    'CodeBlock',
    'Code block renderer with host-owned copy.',
    'optional',
    'Built-in',
    'Clipboard behavior is delegated to the host.',
    '<CodeBlock code={code} />',
  ],
  [
    'Renderers',
    'MessageRendererBoundary',
    'Fallback boundary for custom message renderers.',
    'optional',
    'Built-in fallback',
    'A failed custom renderer does not remove the message.',
    '<MessageRendererBoundary>{children}</MessageRendererBoundary>',
  ],
  [
    'Controls',
    'SendButton',
    'Send control with accessible label and disabled state.',
    'optional',
    'Built-in control',
    'Keep the minimum touch target when replacing it.',
    '<SendButton disabled={disabled} />',
  ],
  [
    'Controls',
    'StopButton',
    'Stop control shown during an active operation.',
    'optional',
    'Built-in control',
    'Stop retains partial response content.',
    '<StopButton onPress={stop} />',
  ],
  [
    'Controls',
    'LoadEarlierControl',
    'History pagination control.',
    'optional',
    'Built-in control',
    'Preserve reading position after prepending.',
    '<LoadEarlierControl onPress={loadEarlier} />',
  ],
  [
    'Controls',
    'ScrollToLatestControl',
    'Return-to-latest control with unread count.',
    'optional',
    'Built-in control',
    'Show it when the reader is away from the bottom.',
    '<ScrollToLatestControl unreadCount={count} />',
  ],
  [
    'Theme',
    'ThemeProvider',
    'Provides semantic theme tokens to component parts.',
    'optional',
    'Light theme',
    'Use the same theme for all custom parts.',
    '<ThemeProvider theme="dark">{children}</ThemeProvider>',
  ],
  [
    'Theme',
    'resolveTheme',
    'Resolves a theme name and partial token overrides.',
    'optional',
    'Light theme',
    'Use semantic tokens rather than hard-coded component layout.',
    'resolveTheme({ name: "high-contrast" })',
  ],
  [
    'Accessibility',
    'useSystemAccessibility',
    'Reads reduced-motion, high-contrast, and text-scale inputs.',
    'optional',
    'System values',
    'Host overrides are applied before custom renderers.',
    'const accessibility = useSystemAccessibility()',
  ],
  [
    'Accessibility',
    'minTouchTarget',
    'Minimum control target helper.',
    'optional',
    'Platform minimum',
    'Do not reduce it in custom controls.',
    'style={{ minHeight: minTouchTarget }}',
  ],
  [
    'Hooks',
    'useAtBottom',
    'Tracks whether the reader is near the latest message.',
    'optional',
    'Threshold default',
    'Use it to gate follow and unread behavior.',
    'const atBottom = useAtBottom(metrics)',
  ],
  [
    'Hooks',
    'useUnreadCount',
    'Computes unseen message count while away from latest.',
    'optional',
    '0',
    'Reset when returning to latest.',
    'const { count } = useUnreadCount(messages)',
  ],
  [
    'Hooks',
    'useAutogrowHeight',
    'Tracks composer growth and internal overflow.',
    'optional',
    'Platform defaults',
    'Keep draft state outside the hook.',
    'const height = useAutogrowHeight(options)',
  ],
  [
    'Hooks',
    'useFocusRing',
    'Provides visible focus styles for controls.',
    'optional',
    'Theme focus style',
    'Apply it to host-supplied interactive controls.',
    'const focus = useFocusRing()',
  ],
]

export const requiredClaims = [
  'WCAG 2.2 AA',
  'screen-reader announcements are out of scope',
  'raw HTML is not rendered',
  'remote images are not loaded by default',
  'does not execute code',
  'host responsibility',
  'composer focus indicator exception',
  'stopped',
  'load earlier',
  'high contrast',
  '200% browser zoom',
  'Touch and mobile',
  '0.3.0',
]

export const recipes = [
  [
    'controlled-chat',
    'Controlled Chat',
    'Own messages, draft, status, submit, stop, and earlier-message loading in the host.',
  ],
  [
    'session-transport',
    'Streaming with useChatSession',
    'Connect an abortable transport and operation-specific chunks without accepting stale updates.',
  ],
  [
    'theme',
    'Theme and high contrast',
    'Use semantic theme tokens, enlarged text, visible focus, and reduced motion.',
  ],
  [
    'renderer',
    'Custom content renderer with fallback',
    'Replace one content renderer while leaving all other content on the safe default.',
  ],
  [
    'actions',
    'Custom actions and composer controls',
    'Add host-owned actions while preserving Send, Stop, draft, and touch targets.',
  ],
  [
    'history',
    'Earlier messages and stable scroll',
    'Prepend history and preserve the reader anchor while unread counts remain meaningful.',
  ],
  [
    'errors',
    'Stopped and failed operations',
    'Retain partial content, mark failed messages, and return conversation status to idle.',
  ],
] as const
